
description: qafact

target:
  service: sing
  # name: vision-amd-cluster
  # name: csr-sing-nlk-sc
  name: vsn-sing-flor-eu
  vc: vision-sing-florence
  # name: amdmi100vc


storage:
  # my_output:
  #   storage_account_name: internexp
  #   container_name: logger
  #   mount_dir: /mnt/myoutput
  #   is_output: True
  cache:
    storage_account_name: internexp
    container_name: chongyan
    mount_dir: /mnt/cache

environment:
  image: amlt-sing/pytorch-1.8.0-cuda11.1-cudnn8-devel
  setup: 
  - bash
  - cd /mnt/cache/
  - git clone https://github.com/maszhongming/UniEval.git
  - cd UniEval
  - pip install -r requirements.txt
  - cp /mnt/cache/Models/eval_unieval.py /mnt/cache/UniEval/eval_unieval.py
  

jobs:
  - name: qafact0
    sla_tier: premium  # Default: premium, 
    execution_mode: basic  # Default: basic
    priority: high  # Default: medium
    sku: 32G1-V100 # 1xG8-V100-IB@westus2,westus3 
    command:
    - cd /mnt/cache/UniEval/
    - python eval_unieval.py
    submit_args:
      max_run_duration_seconds: 1080000
      # env:
      #   NCCL_IB_DISABLE: 0 # 
      #   NNCL_DEBUG: VERSION # 
      #   NCCL_IB_TIMEOUT: 22 # suggested by Hua
      #   MKL_THREADING_LAYER: GNU
      env:
        # AMLT_NO_TENSORBOARD_PATCHING: 1
        NCCL_IB_DISABLE: 0
        NCCL_IBEXT_DISABLE: 0
        NCCL_DEBUG: INFO
        NCCL_IB_TIMEOUT: 22
        MKL_THREADING_LAYER: GNU
        ENABLE_HOME_MOUNT: False
        MIOPEN_FIND_MODE: 1
        DATASET_FUSE_CACHE_TIMEOUT: 0