
description: qafact

target:
  service: sing
  # name: vision-amd-cluster
  name: csr-sing-nlk-sc
  # name: amdmi100vc


storage:
  my_output:
    storage_account_name: cqa
    container_name: logger
    mount_dir: /mnt/myoutput
    is_output: True
  cache:
    storage_account_name: cqa
    container_name: ccqa

environment:
  image: amlt-sing/pytorch-1.8.0-cuda11.1-cudnn8-devel
  setup: 
  - bash
  - pip install pandas
  - cd /mnt/cache/
  - pip uninstall torch
  - pip install torch==1.6.0
  - git clone https://github.com/salesforce/QAFactEval
  - cd QAFactEval
  - pip install -e .
  - cd /mnt/cache/Models
  

jobs:
  - name: qafact0
    sla_tier: premium  # Default: premium, 
    execution_mode: basic  # Default: basic
    priority: high  # Default: medium
    sku: 32G1-V100 # 1xG8-V100-IB@westus2,westus3 
    command:
    - cd /mnt/cache/Models
    - python eval_QAFACT.py 0
    # - python -m llava.eval.run_llava       --model-name /mnt/cache/LLaVA-13B-v0       --image-file "https://llava-vl.github.io/static/images/view.jpg" --query "What are the things I should be cautious about when I visit here?"
    # - python -m llava.eval.model_vqa --model-name /mnt/cache/LLaVA-13B-v0 --question-file /mnt/cache/FinalInput/llava_input_merged.jsonl    --image-folder  /mnt/cache/images_jpg_1500_merge_ori_index  --answers-file /mnt/cache/ModelPrediction/llava_prediction_merged_small.jsonl  --num-chunks 20 --chunk-idx 1
  - name: qafact1
    sla_tier: premium  # Default: premium, 
    execution_mode: basic  # Default: basic
    priority: high  # Default: medium
    sku: 32G1-V100 # 1xG8-V100-IB@westus2,westus3 
    command:
    - cd /mnt/cache/Models
    - python eval_QAFACT.py 1
    # - python -m llava.eval.run_llava       --model-name /mnt/cache/LLaVA-13B-v0       --image-file "https://llava-vl.github.io/static/images/view.jpg" --query "What are the things I should be cautious about when I visit here?"
    # - python -m llava.eval.model_vqa --model-name /mnt/cache/LLaVA-13B-v0 --question-file /mnt/cache/FinalInput/llava_input_merged.jsonl    --image-folder  /mnt/cache/images_jpg_1500_merge_ori_index  --answers-file /mnt/cache/ModelPrediction/llava_prediction_merged_small.jsonl  --num-chunks 20 --chunk-idx 1
  - name: qafact2
    sla_tier: premium  # Default: premium, 
    execution_mode: basic  # Default: basic
    priority: high  # Default: medium
    sku: 32G1-V100 # 1xG8-V100-IB@westus2,westus3 
    command:
    - cd /mnt/cache/Models
    - python eval_QAFACT.py 2
    # - python -m llava.eval.run_llava       --model-name /mnt/cache/LLaVA-13B-v0       --image-file "https://llava-vl.github.io/static/images/view.jpg" --query "What are the things I should be cautious about when I visit here?"
    # - python -m llava.eval.model_vqa --model-name /mnt/cache/LLaVA-13B-v0 --question-file /mnt/cache/FinalInput/llava_input_merged.jsonl    --image-folder  /mnt/cache/images_jpg_1500_merge_ori_index  --answers-file /mnt/cache/ModelPrediction/llava_prediction_merged_small.jsonl  --num-chunks 20 --chunk-idx 1
  - name: qafact3
    sla_tier: premium  # Default: premium, 
    execution_mode: basic  # Default: basic
    priority: high  # Default: medium
    sku: 32G1-V100 # 1xG8-V100-IB@westus2,westus3 
    command:
    - cd /mnt/cache/Models
    - python eval_QAFACT.py 3
  