
description: eval Blip2

target:
  # service: amlk8s
  # name: a100-80gb-wus3
  # vc: csr-itp-nlm


  service: sing
  name: csr-sing-wu2 #csr-sing-nlk-sc


  # name: vision-amd-cluster
  # name: amdmi100vc


storage:
  my_output:
    storage_account_name: cqa
    container_name: ccqa
    mount_dir: /mnt/myoutput
    is_output: True
  cache:
    storage_account_name: cqa
    container_name: ccqa
    mount_dir: /mnt/cache

environment:
  image: amlt-sing/pytorch-1.11.0
  # image: bitnami/pytorch:latest
  setup: 
  - bash
  - cd /mnt/cache/
  - pip install torch==2.0.1
  - pip install torchtext
  - pip install torchvision==0.15.2
  - pip install accelerate
  
  
  - cd LAVIS2
  # - pip install salesforce-lavis
  # - git clone https://github.com/salesforce/LAVIS.git
  - cd LAVIS
  - pip install -e .
  - pip install protobuf==3.20.0

jobs:
  # - name: flantxxlqmLenLong
  #   # preemptible: True
  #   sla_tier: premium  # Default: premium, 
  #   execution_mode: basic  # Default: basic
  #   priority: high  # Default: medium
  #   # sku: 64G1-A100 # 1xG8-V100-IB@westus2,westus3
  #   sku: 32G1-V100
  #   command:
  #     - echo "now in job command!"
  #     - cd /mnt/cache/blip2
  #     # - pip install -e .
  #     - python blip2_from_source.py 2 0 1 #1 -xl, 2-xxl; 0:q+m;
  # - name: flantxlqmLenLong
  #   # preemptible: True
  #   sla_tier: premium  # Default: premium, 
  #   execution_mode: basic  # Default: basic
  #   priority: high  # Default: medium
  #   # sku: 64G1-A100 # 1xG8-V100-IB@westus2,westus3
  #   sku: 32G1-V100
  #   command:
  #     - echo "now in job command!"
  #     - cd /mnt/cache/blip2
  #     # - pip install -e .
  #     - python blip2_from_source.py 1 0 1 #1 -xl, 2-xxl; 0:q+m;
  - name: flantxlVQAinW
    # preemptible: True
    sla_tier: premium  # Default: premium, 
    execution_mode: basic  # Default: basic
    priority: high  # Default: medium
    # sku: 64G1-A100 # 1xG8-V100-IB@westus2,westus3
    sku: 32G1-V100
    command:
      - echo "now in job command!"
      - cd /mnt/cache/blip2
      # - pip install -e .
      - python blip2_VQAinW.py 1 0 1 #1 -xl, 2-xxl; 0:q+m;
