
description: eval Blip2

target:
  # service: amlk8s
  # name: a100-80gb-wus3
  # vc: csr-itp-nlm
  service: sing
  name: vsn-sing-flor-eu
  vc: vision-sing-florence

  # name: csr-sing-wu2 #csr-sing-nlk-sc


  # name: vision-amd-cluster
  # name: amdmi100vc

storage:
  cache:
    storage_account_name: internexp
    container_name: chongyan
    mount_dir: /mnt/cache
environment:
  image: amlt-sing/pytorch-1.11.0
  # image: bitnami/pytorch:latest
  setup: 
  - bash
  - cd /mnt/cache/
  - pip install torch==2.0.1
  - pip install torchtext
  - pip install torchvision==0.15.2
  - pip install accelerate
  
  
  - cd LAVIS2
  # - pip install salesforce-lavis
  # - git clone https://github.com/salesforce/LAVIS.git
  - cd LAVIS
  - pip install -e .
  - pip install protobuf==3.20.0

jobs:
  - name: flantxlVQAinW1
    # preemptible: True
    sla_tier: premium  # Default: premium, 
    execution_mode: basic  # Default: basic
    priority: high  # Default: medium
    # sku: 64G1-A100 # 1xG8-V100-IB@westus2,westus3
    sku: 32G1-V100
    command:
      - echo "now in job command!"
      - cd /mnt/cache/Models/
      - python blip2_VQAinW.py 1 0 1 1 > /mnt/cache/logs/BLIP2.log 2>&1 

    submit_args:  
      max_run_duration_seconds: 1080000
      env:
        NCCL_IB_DISABLE: 0
        NCCL_IBEXT_DISABLE: 0
        NCCL_DEBUG: INFO
        NCCL_IB_TIMEOUT: 22
        MKL_THREADING_LAYER: GNU
        ENABLE_HOME_MOUNT: False
        MIOPEN_FIND_MODE: 1
        DATASET_FUSE_CACHE_TIMEOUT: 0

  - name: flantxlVQAinW2
    # preemptible: True
    sla_tier: premium  # Default: premium, 
    execution_mode: basic  # Default: basic
    priority: high  # Default: medium
    # sku: 64G1-A100 # 1xG8-V100-IB@westus2,westus3
    sku: 32G1-V100
    command:
      - echo "now in job command!"
      - cd /mnt/cache/Models/
      - python blip2_VQAinW.py 1 0 1 2 > /mnt/cache/logs/BLIP2.log 2>&1 

    submit_args:  
      max_run_duration_seconds: 1080000
      env:
        NCCL_IB_DISABLE: 0
        NCCL_IBEXT_DISABLE: 0
        NCCL_DEBUG: INFO
        NCCL_IB_TIMEOUT: 22
        MKL_THREADING_LAYER: GNU
        ENABLE_HOME_MOUNT: False
        MIOPEN_FIND_MODE: 1
        DATASET_FUSE_CACHE_TIMEOUT: 0

  - name: flantxlVQAinW3
    # preemptible: True
    sla_tier: premium  # Default: premium, 
    execution_mode: basic  # Default: basic
    priority: high  # Default: medium
    # sku: 64G1-A100 # 1xG8-V100-IB@westus2,westus3
    sku: 32G1-V100
    command:
      - echo "now in job command!"
      - cd /mnt/cache/Models/
      - python blip2_VQAinW.py 1 0 1 3 > /mnt/cache/logs/BLIP2.log 2>&1 

    submit_args:  
      max_run_duration_seconds: 1080000
      env:
        NCCL_IB_DISABLE: 0
        NCCL_IBEXT_DISABLE: 0
        NCCL_DEBUG: INFO
        NCCL_IB_TIMEOUT: 22
        MKL_THREADING_LAYER: GNU
        ENABLE_HOME_MOUNT: False
        MIOPEN_FIND_MODE: 1
        DATASET_FUSE_CACHE_TIMEOUT: 0
  
  - name: flantxlVQAinW4
    # preemptible: True
    sla_tier: premium  # Default: premium, 
    execution_mode: basic  # Default: basic
    priority: high  # Default: medium
    # sku: 64G1-A100 # 1xG8-V100-IB@westus2,westus3
    sku: 32G1-V100
    command:
      - echo "now in job command!"
      - cd /mnt/cache/Models/
      - python blip2_VQAinW.py 1 0 1 4 > /mnt/cache/logs/BLIP2.log 2>&1 

    submit_args:  
      max_run_duration_seconds: 1080000
      env:
        NCCL_IB_DISABLE: 0
        NCCL_IBEXT_DISABLE: 0
        NCCL_DEBUG: INFO
        NCCL_IB_TIMEOUT: 22
        MKL_THREADING_LAYER: GNU
        ENABLE_HOME_MOUNT: False
        MIOPEN_FIND_MODE: 1
        DATASET_FUSE_CACHE_TIMEOUT: 0

  - name: flantxlVQAinW5
    # preemptible: True
    sla_tier: premium  # Default: premium, 
    execution_mode: basic  # Default: basic
    priority: high  # Default: medium
    # sku: 64G1-A100 # 1xG8-V100-IB@westus2,westus3
    sku: 32G1-V100
    command:
      - echo "now in job command!"
      - cd /mnt/cache/Models/
      - python blip2_VQAinW.py 1 0 1 5 > /mnt/cache/logs/BLIP2.log 2>&1 

    submit_args:  
      max_run_duration_seconds: 1080000
      env:
        NCCL_IB_DISABLE: 0
        NCCL_IBEXT_DISABLE: 0
        NCCL_DEBUG: INFO
        NCCL_IB_TIMEOUT: 22
        MKL_THREADING_LAYER: GNU
        ENABLE_HOME_MOUNT: False
        MIOPEN_FIND_MODE: 1
        DATASET_FUSE_CACHE_TIMEOUT: 0
  
  - name: flantxlVQAinW6
    # preemptible: True
    sla_tier: premium  # Default: premium, 
    execution_mode: basic  # Default: basic
    priority: high  # Default: medium
    # sku: 64G1-A100 # 1xG8-V100-IB@westus2,westus3
    sku: 32G1-V100
    command:
      - echo "now in job command!"
      - cd /mnt/cache/Models/
      - python blip2_VQAinW.py 1 0 1 6 > /mnt/cache/logs/BLIP2.log 2>&1 

    submit_args:  
      max_run_duration_seconds: 1080000
      env:
        NCCL_IB_DISABLE: 0
        NCCL_IBEXT_DISABLE: 0
        NCCL_DEBUG: INFO
        NCCL_IB_TIMEOUT: 22
        MKL_THREADING_LAYER: GNU
        ENABLE_HOME_MOUNT: False
        MIOPEN_FIND_MODE: 1
        DATASET_FUSE_CACHE_TIMEOUT: 0
  
  - name: flantxlVQAinW7
    # preemptible: True
    sla_tier: premium  # Default: premium, 
    execution_mode: basic  # Default: basic
    priority: high  # Default: medium
    # sku: 64G1-A100 # 1xG8-V100-IB@westus2,westus3
    sku: 32G1-V100
    command:
      - echo "now in job command!"
      - cd /mnt/cache/Models/
      - python blip2_VQAinW.py 1 0 1 7 > /mnt/cache/logs/BLIP2.log 2>&1 

    submit_args:  
      max_run_duration_seconds: 1080000
      env:
        NCCL_IB_DISABLE: 0
        NCCL_IBEXT_DISABLE: 0
        NCCL_DEBUG: INFO
        NCCL_IB_TIMEOUT: 22
        MKL_THREADING_LAYER: GNU
        ENABLE_HOME_MOUNT: False
        MIOPEN_FIND_MODE: 1
        DATASET_FUSE_CACHE_TIMEOUT: 0
  
  - name: flantxlVQAinW8
    # preemptible: True
    sla_tier: premium  # Default: premium, 
    execution_mode: basic  # Default: basic
    priority: high  # Default: medium
    # sku: 64G1-A100 # 1xG8-V100-IB@westus2,westus3
    sku: 32G1-V100
    command:
      - echo "now in job command!"
      - cd /mnt/cache/Models/
      - python blip2_VQAinW.py 1 0 1 8 > /mnt/cache/logs/BLIP2.log 2>&1 

    submit_args:  
      max_run_duration_seconds: 1080000
      env:
        NCCL_IB_DISABLE: 0
        NCCL_IBEXT_DISABLE: 0
        NCCL_DEBUG: INFO
        NCCL_IB_TIMEOUT: 22
        MKL_THREADING_LAYER: GNU
        ENABLE_HOME_MOUNT: False
        MIOPEN_FIND_MODE: 1
        DATASET_FUSE_CACHE_TIMEOUT: 0