description: debug

target:
  service: amlk8s
  # run "pt target list amlk8s" to list the names of available AMLK8s targets
  vc: vision-itp-florence
  name: v100-32gb-eus



environment:
  image: horovod/horovod:0.20.0-tf2.3.0-torch1.6.0-mxnet1.6.0.post0-py3.7-cuda10.1
  setup:
  - ls
  - bash clone.sh
  - pip install torch==1.8.1+cu101 torchvision==0.9.1+cu101 torchaudio==0.8.1 -f https://download.pytorch.org/whl/torch_stable.html
  - cd ./FastMoE
  - git checkout -b mae origin/mae
  - pip install --upgrade pip
  - pip install opencv-python==4.4.0.46 termcolor==1.1.0 yacs==0.1.8
  - pip install timm==0.4.12
  - sudo apt-get update ##[edited]
  - sudo apt-get install ffmpeg libsm6 libxext6 -y
  - python -m pip install -r requirements.txt --user -q
  - python -m pip install numpy --user -q
  - python -m pip install Pillow==8.2.0 --user -q
  - cd ./fastmoe_custom
  - USE_NCCL=1 python setup.py install --user
  - cd ../
  - git clone https://github.com/microsoft/tutel
  - cd tutel
  - git checkout e51df1ca64be59eae3691bc1c64b20a201de1009
  - python -m pip install -e .
  - python -m pip install mpi4py
  - cd ../
  - ls
  - pip install scipy --user -q
  - cd ./mae
  - cd ./ort_moe
  - python -m pip install -e . --user -q
  - python -m pip install einops --user -q


storage:
  output:
    storage_account_name: internexp
    container_name: lmwu-vit-1k-pair
    mount_dir: /mnt/output
  dataset:
    storage_account_name: pubdataseteuv2
    container_name: imagenet
    mount_dir: /mnt/dataset


code:
  local_dir: ~/workspace/dummy_code/lemeng/

jobs:
- name: debug
  sku: 2xG8
  mpi: True
  process_count_per_node: 8
  command:
  - ls
  - cd ./FastMoE
  - ls
  - cd ./mae
  - bash run_8e_fastmoe_small_128.sh
  submit_args:
    env:
      NCCL_IB_DISABLE: 0
      NCCL_DEBUG: INFO
      NCCL_IB_TIMEOUT: 22
      MKL_THREADING_LAYER: GNU
