
description: eval gpt4

target:
  service: sing
  name: vsn-sing-flor-eu
  vc: vision-sing-florence

storage:
  cache:
    storage_account_name: internexp
    container_name: chongyan
    mount_dir: /mnt/cache
environment:
  image: amlt-sing/pytorch-1.11.0
  # image: bitnami/pytorch:latest
  setup: 
  - bash
  - cd /mnt/cache/Models/gpt4
  - pip install -r requirements.txt
  
jobs:
  - name: gpt4
    # preemptible: True
    sla_tier: premium  # Default: premium, 
    execution_mode: basic  # Default: basic
    priority: high  # Default: medium
    # sku: 64G1-A100 # 1xG8-V100-IB@westus2,westus3
    sku: 32G1-V100
    command:
      - echo "now in job command!"
      - cd /mnt/cache/Models/gpt4
      - gpt4.py --azure="azure" --read /mnt/cache/Models/gpt4/sampled_test.csv --write /mnt/cache/annotations/VQAinW_gpt4.json

    submit_args:  
      max_run_duration_seconds: 1080000
      env:
        NCCL_IB_DISABLE: 0
        NCCL_IBEXT_DISABLE: 0
        NCCL_DEBUG: INFO
        NCCL_IB_TIMEOUT: 22
        MKL_THREADING_LAYER: GNU
        ENABLE_HOME_MOUNT: False
        MIOPEN_FIND_MODE: 1
        DATASET_FUSE_CACHE_TIMEOUT: 0
        