
description: eval mPlug

target:
  service: sing
  # name: vision-amd-cluster
  # name: csr-sing-nlk-sc
  # name: amdmi100vc
  name: vsn-sing-flor-eu
  vc: vision-sing-florence



storage:
  cache:
    storage_account_name: internexp
    container_name: chongyan
    mount_dir: /mnt/cache

environment:
  image: amlt-sing/acpt-pytorch-1.13.0-cuda11.7
  setup: 
  - bash
  - cd /mnt/cache/
  # - rm -r mPLUG-Owl
  # - git clone https://github.com/X-PLUG/mPLUG-Owl.git
  # - cp /mnt/cache/Models/owl_CI.py /mnt/cache/mPLUG-Owl/owl_CI.py
  - cd mPLUG-Owl
  - pip install torch==1.13.1 torchvision==0.14.1 torchaudio==0.13.1
  - pip install -r requirements.txt
  - pip install pandas
  - export PROTOCOL_BUFFERS_PYTHON_IMPLEMENTATION=python
  - cd /mnt/cache/mPLUG-Owl
  - pip install -r requirements.txt


jobs:
  - name: mPlug1
    sla_tier: premium  # Default: premium, 
    execution_mode: basic  # Default: basic
    priority: high  # Default: medium
    sku: 32G1-V100 # 1xG8-V100-IB@westus2,westus3 
    command:
    - cd /mnt/cache/mPLUG-Owl
    - python owl_CI.py 1 > /mnt/cache/logs/mplug_CI.log 2>&1 
 
    submit_args:
      max_run_duration_seconds: 1080000
      env:
        NCCL_IB_DISABLE: 0
        NCCL_IBEXT_DISABLE: 0
        NCCL_DEBUG: INFO
        NCCL_IB_TIMEOUT: 22
        MKL_THREADING_LAYER: GNU
        ENABLE_HOME_MOUNT: False
        MIOPEN_FIND_MODE: 1
        DATASET_FUSE_CACHE_TIMEOUT: 0
  - name: mPlug2
    sla_tier: premium  # Default: premium, 
    execution_mode: basic  # Default: basic
    priority: high  # Default: medium
    sku: 32G1-V100 # 1xG8-V100-IB@westus2,westus3 
    command:
    - cd /mnt/cache/mPLUG-Owl
    - python owl_CI.py 2
 
    submit_args:
      max_run_duration_seconds: 1080000
      env:
        NCCL_IB_DISABLE: 0
        NCCL_IBEXT_DISABLE: 0
        NCCL_DEBUG: INFO
        NCCL_IB_TIMEOUT: 22
        MKL_THREADING_LAYER: GNU
        ENABLE_HOME_MOUNT: False
        MIOPEN_FIND_MODE: 1
        DATASET_FUSE_CACHE_TIMEOUT: 0
  - name: mPlug3
    sla_tier: premium  # Default: premium, 
    execution_mode: basic  # Default: basic
    priority: high  # Default: medium
    sku: 32G1-V100 # 1xG8-V100-IB@westus2,westus3 
    command:
    - cd /mnt/cache/mPLUG-Owl
    - python owl_CI.py 3
 
    submit_args:
      max_run_duration_seconds: 1080000
      env:
        NCCL_IB_DISABLE: 0
        NCCL_IBEXT_DISABLE: 0
        NCCL_DEBUG: INFO
        NCCL_IB_TIMEOUT: 22
        MKL_THREADING_LAYER: GNU
        ENABLE_HOME_MOUNT: False
        MIOPEN_FIND_MODE: 1
        DATASET_FUSE_CACHE_TIMEOUT: 0
  - name: mPlug4
    sla_tier: premium  # Default: premium, 
    execution_mode: basic  # Default: basic
    priority: high  # Default: medium
    sku: 32G1-V100 # 1xG8-V100-IB@westus2,westus3 
    command:
    - cd /mnt/cache/mPLUG-Owl
    - python owl_CI.py 4
 
    submit_args:
      max_run_duration_seconds: 1080000
      env:
        NCCL_IB_DISABLE: 0
        NCCL_IBEXT_DISABLE: 0
        NCCL_DEBUG: INFO
        NCCL_IB_TIMEOUT: 22
        MKL_THREADING_LAYER: GNU
        ENABLE_HOME_MOUNT: False
        MIOPEN_FIND_MODE: 1
        DATASET_FUSE_CACHE_TIMEOUT: 0
  - name: mPlug5
    sla_tier: premium  # Default: premium, 
    execution_mode: basic  # Default: basic
    priority: high  # Default: medium
    sku: 32G1-V100 # 1xG8-V100-IB@westus2,westus3 
    command:
    - cd /mnt/cache/mPLUG-Owl
    - python owl_CI.py 5
 
    submit_args:
      max_run_duration_seconds: 1080000
      env:
        NCCL_IB_DISABLE: 0
        NCCL_IBEXT_DISABLE: 0
        NCCL_DEBUG: INFO
        NCCL_IB_TIMEOUT: 22
        MKL_THREADING_LAYER: GNU
        ENABLE_HOME_MOUNT: False
        MIOPEN_FIND_MODE: 1
        DATASET_FUSE_CACHE_TIMEOUT: 0
  - name: mPlug6
    sla_tier: premium  # Default: premium, 
    execution_mode: basic  # Default: basic
    priority: high  # Default: medium
    sku: 32G1-V100 # 1xG8-V100-IB@westus2,westus3 
    command:
    - cd /mnt/cache/mPLUG-Owl
    - python owl_CI.py 6
 
    submit_args:
      max_run_duration_seconds: 1080000
      env:
        NCCL_IB_DISABLE: 0
        NCCL_IBEXT_DISABLE: 0
        NCCL_DEBUG: INFO
        NCCL_IB_TIMEOUT: 22
        MKL_THREADING_LAYER: GNU
        ENABLE_HOME_MOUNT: False
        MIOPEN_FIND_MODE: 1
        DATASET_FUSE_CACHE_TIMEOUT: 0
  - name: mPlug7
    sla_tier: premium  # Default: premium, 
    execution_mode: basic  # Default: basic
    priority: high  # Default: medium
    sku: 32G1-V100 # 1xG8-V100-IB@westus2,westus3 
    command:
    - cd /mnt/cache/mPLUG-Owl
    - python owl_CI.py 7
 
    submit_args:
      max_run_duration_seconds: 1080000
      env:
        NCCL_IB_DISABLE: 0
        NCCL_IBEXT_DISABLE: 0
        NCCL_DEBUG: INFO
        NCCL_IB_TIMEOUT: 22
        MKL_THREADING_LAYER: GNU
        ENABLE_HOME_MOUNT: False
        MIOPEN_FIND_MODE: 1
        DATASET_FUSE_CACHE_TIMEOUT: 0
  - name: mPlug8
    sla_tier: premium  # Default: premium, 
    execution_mode: basic  # Default: basic
    priority: high  # Default: medium
    sku: 32G1-V100 # 1xG8-V100-IB@westus2,westus3 
    command:
    - cd /mnt/cache/mPLUG-Owl
    - python owl_CI.py 8
 
    submit_args:
      max_run_duration_seconds: 1080000
      env:
        NCCL_IB_DISABLE: 0
        NCCL_IBEXT_DISABLE: 0
        NCCL_DEBUG: INFO
        NCCL_IB_TIMEOUT: 22
        MKL_THREADING_LAYER: GNU
        ENABLE_HOME_MOUNT: False
        MIOPEN_FIND_MODE: 1
        DATASET_FUSE_CACHE_TIMEOUT: 0